### ISSUE TITLE
Changes in Signup/Login

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#117]
https://discord.com/channels/717601425630429197/778779840903249961/844514415922380800

**Páginas de cadastro/login.** 

1. Mudar a frase: Welcome to the movement to heal planet Earth! para: Welcome to the community that is creating a more beautiful world. 

Mudar a frase: We value and respect your data! That's why it will never be traded with third parties. We stand for total transparency and ethics!
Para:  We respect and protect your personal data. Check here our pledge for transparency and high ethical standards. (Obs: "Check here" deve ser linkado com essa page: https://www.ootopia.org/pledge)

2. Box de preenchimento das infos pessoais. A palavra dentro do box (e-mail ou password por exemplo) deve desaparecer quando a pessoa clica no box para escrever. Nos Boxes de texto como o Name and Surname a digitação deve começar automaticamente com letra maiúscula.

3. Adicionar no box da senha a opção de visualização da senha.

**Comment by AndrewDiass** [comment]
- [ ] Mudar a frase: Welcome to the movement to heal planet Earth! para: Welcome to the community that is creating a more beautiful world.
Mudar a frase: We value and respect your data! That's why it will never be traded with third parties. We stand for total transparency and ethics!
Para: We respect and protect your personal data. Check here our pledge for transparency and high ethical standards. (Obs: "Check here" deve ser linkado com essa page: https://www.ootopia.org/pledge)

- [ ] Box de preenchimento das infos pessoais. A palavra dentro do box (e-mail ou password por exemplo) deve desaparecer quando a pessoa clica no box para escrever. Nos Boxes de texto como o Name and Surname a digitação deve começar automaticamente com letra maiúscula.

- [ ] Adicionar no box da senha a opção de visualização da senha.
